### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by Luoyingliang** [Marusyk/BinaryTree#4]
Hi, Guys.I am a Chinese Programmer.this is my first issue in English,perhap the issue will be unreadable,I mean my speech maybe  very terrible ,but please read this suggestion.
I Suggested that wee can changed TraversalStrategy class type from class to interface

**Comment by Marusyk** [comment]
Hi @Luoyingliang, Thanks for your suggestion. I think it is a good idea. Feel free to create Pull request with that changes.

**Comment by Marusyk** [comment]
Done
