### ISSUE TITLE
Tips, improvements, suggestions

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/BinaryTree#9]
This project is a simple implementation of binary tree. It would be greate to have some suggestions how it can be improved. Maybe some ideas for new features.

**Comment by chrsi** [comment]
What do you think about a pretty print function?

**Comment by Marusyk** [comment]
Hi @chrsi, yes please. I will wait for PR

**Comment by kanilZ** [comment]
Maybe will be good feature to delete sub tree. Also to add sub tree to specified node
